/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Manufacturer;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InventoryOrderRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author srinivasarithikghantasala
 */
public class TestingWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestingWorkAreaJPanel
     */
    JPanel workArea;
    EcoSystem system;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    public TestingWorkAreaJPanel(JPanel workArea, UserAccount account,Organization organization,Enterprise enterprise , EcoSystem system) {
        initComponents();
        this.workArea = workArea;
        this.system = system;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkArea = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnManf = new javax.swing.JButton();
        btnViewOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblWorkArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Model", "Quantity", "Testing", "Manufacturer Technical", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkArea);

        btnAssign.setText("Assign to me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnManf.setText("Testing Done");
        btnManf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManfActionPerformed(evt);
            }
        });

        btnViewOrder.setText("View Order");
        btnViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Testing Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAssign)
                                .addGap(347, 347, 347)
                                .addComponent(btnViewOrder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnManf, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssign)
                    .addComponent(btnViewOrder)
                    .addComponent(btnManf))
                .addGap(143, 143, 143))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblWorkArea.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Pick a selected row", "Information", JOptionPane.INFORMATION_MESSAGE);

            return;
        }

        InventoryOrderRequest req = (InventoryOrderRequest)tblWorkArea.getValueAt(selectedRow, 0);
        if(req.getTesting()!= null){
            JOptionPane.showMessageDialog(this, "Already assigned", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(req.getIsPaint()==false){
            JOptionPane.showMessageDialog(this, "Cannot be assigned now", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(req.getIsManf()==false){
            JOptionPane.showMessageDialog(this, "Cannot be assigned now", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(req.getIsTech()==false){
            JOptionPane.showMessageDialog(this, "Cannot be assigned now", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        req.setTesting(account);
        req.setStatus("Testing assigned");
        populateRequestTable();
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnManfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManfActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblWorkArea.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Pick a selected row", "Information", JOptionPane.INFORMATION_MESSAGE);

            return;
        }

        InventoryOrderRequest req = (InventoryOrderRequest)tblWorkArea.getValueAt(selectedRow, 0);
        if(req.getTesting() != account){
            JOptionPane.showMessageDialog(this, "It is not assigned to you!!", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        else if (req.getTesting() == account && req.getIsManf()==true && req.getIsPaint()==true && req.getIsTech()==true && req.getIsTest()==false){
            req.setStatus("Testing Done !!");
            req.setIsTest(true);
            JOptionPane.showMessageDialog(this, "Status Updated !!", "Information", JOptionPane.INFORMATION_MESSAGE);
            populateRequestTable();
            return;
        }
        else if(req.getIsManf()==false){
            JOptionPane.showMessageDialog(this, "First Manufacturing is not done !!", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        else if(req.getIsPaint()==false){
            JOptionPane.showMessageDialog(this, "Paint is not Manufactured!!", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        else if(req.getIsTech()==false){
            JOptionPane.showMessageDialog(this, "Technical is not Manufactured!!", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        else if(req.getIsTest()==true){
            JOptionPane.showMessageDialog(this, "Already Manufactured!!", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        populateRequestTable();
    }//GEN-LAST:event_btnManfActionPerformed

    private void btnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblWorkArea.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Pick a selected row", "Information", JOptionPane.INFORMATION_MESSAGE);

            return;
        }

        InventoryOrderRequest req = (InventoryOrderRequest)tblWorkArea.getValueAt(selectedRow, 0);

        ViewOrderInfoJPanel viojp = new ViewOrderInfoJPanel(workArea, req);
        workArea.add("ViewOrderInfoJPanel",viojp);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_btnViewOrderActionPerformed
public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) tblWorkArea.getModel();
        
        model.setRowCount(0);

        for(Network network:system.getNetworkList()){
            for(Enterprise ent: network.getEnterpriseDirectory().getEnterpriseList()){
                if (ent.getName().equals(enterprise.getName())){
                    for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
                        if(org.getName().equals(organization.getName())){
                            for(InventoryOrderRequest req : org.getInventoryOrderQueue().getInventoryOrderRequestList()){
                                    Object[] row = new Object[6];
                                    row[0] = req;
                                    row[1] = req.getCar().getModel();
                                    row[2] = req.getQuantity();
                                    row[3] = req.getTesting()==null?"None":req.getTesting().getUsername();
                                    row[4] = req.getManufacturerTechnical()==null?"None":req.getManufacturerTechnical().getUsername();
                                    row[5] = req.getStatus();

                                    model.addRow(row);
                            }
                        }
                    }
                    
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnManf;
    private javax.swing.JButton btnViewOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblWorkArea;
    // End of variables declaration//GEN-END:variables
}
