/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Customer;

/**
 *
 * @author manasvini
 */
public class CustomerRequestDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerRequestDetailsJPanel
     */
    public CustomerRequestDetailsJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labCustomerRequest = new javax.swing.JLabel();
        labDealer = new javax.swing.JLabel();
        labCarDetails = new javax.swing.JLabel();
        labModelName = new javax.swing.JLabel();
        labEngine = new javax.swing.JLabel();
        labColor = new javax.swing.JLabel();
        ButtonRequestOrder = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();
        labTransmission = new javax.swing.JLabel();
        ComboBoxDealer = new javax.swing.JComboBox<>();
        ComboBoxCarDetails = new javax.swing.JComboBox<>();
        ComboBoxModelName = new javax.swing.JComboBox<>();
        ComboBoxColor = new javax.swing.JComboBox<>();
        ComboBoxEngine = new javax.swing.JComboBox<>();
        ComboBoxTransmission = new javax.swing.JComboBox<>();

        labCustomerRequest.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        labCustomerRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labCustomerRequest.setText("CUSTOMER REQUEST DETAILS");

        labDealer.setText("Dealer :");

        labCarDetails.setText("Car Details :");

        labModelName.setText("Model Name :");

        labEngine.setText("Engine :");

        labColor.setText("Color :");

        ButtonRequestOrder.setText("Request Order");

        ButtonBack.setText(">>Back");

        labTransmission.setText("Transmission :");

        ComboBoxDealer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ComboBoxCarDetails.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ComboBoxModelName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ComboBoxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ComboBoxEngine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ComboBoxTransmission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labCustomerRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(ButtonBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonRequestOrder)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labDealer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labCarDetails, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labModelName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labColor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labEngine, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labTransmission, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComboBoxDealer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxCarDetails, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxModelName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxColor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxEngine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(labCustomerRequest)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDealer)
                    .addComponent(ComboBoxDealer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCarDetails)
                    .addComponent(ComboBoxCarDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labModelName)
                    .addComponent(ComboBoxModelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labColor)
                    .addComponent(ComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labEngine)
                    .addComponent(ComboBoxEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTransmission)
                    .addComponent(ComboBoxTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRequestOrder)
                    .addComponent(ButtonBack))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonRequestOrder;
    private javax.swing.JComboBox<String> ComboBoxCarDetails;
    private javax.swing.JComboBox<String> ComboBoxColor;
    private javax.swing.JComboBox<String> ComboBoxDealer;
    private javax.swing.JComboBox<String> ComboBoxEngine;
    private javax.swing.JComboBox<String> ComboBoxModelName;
    private javax.swing.JComboBox<String> ComboBoxTransmission;
    private javax.swing.JLabel labCarDetails;
    private javax.swing.JLabel labColor;
    private javax.swing.JLabel labCustomerRequest;
    private javax.swing.JLabel labDealer;
    private javax.swing.JLabel labEngine;
    private javax.swing.JLabel labModelName;
    private javax.swing.JLabel labTransmission;
    // End of variables declaration//GEN-END:variables
}
