/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Customer;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PricingOrderRequest;
import Business.WorkQueue.QuoteOrderRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author srinivasarithikghantasala
 */



public class RequestQuoteJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestQuoteJPanel
     */
    JPanel workArea;
    EcoSystem system;
    UserAccount account;
    Random random = new Random();
    public RequestQuoteJPanel(JPanel workArea, UserAccount account, EcoSystem system) {
        initComponents();
        this.workArea = workArea;
        this.system = system;
        this.account = account;
        setSize(750, 530);
        initCmb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbModel = new javax.swing.JComboBox<>();
        cmbVariant = new javax.swing.JComboBox<>();
        cmbIntColor = new javax.swing.JComboBox<>();
        CmbExtColor = new javax.swing.JComboBox<>();
        cmbTrans = new javax.swing.JComboBox<>();
        cmbEngine = new javax.swing.JComboBox<>();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbDealer = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Model Name :");

        jLabel2.setText("Variant :");

        jLabel3.setText("Interior Color :");

        jLabel4.setText("Exterior Color :");

        jLabel5.setText("Transmission :");

        jLabel6.setText("Engine :");

        cmbModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbVariant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbIntColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CmbExtColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbTrans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbEngine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCreate.setText("Request a Quote");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Request a Quote");

        jLabel9.setText("Dealer :");

        cmbDealer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Manufacturing5.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cmbDealer, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbVariant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbIntColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CmbExtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbModel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCreate))))
                        .addGap(47, 47, 47)
                        .addComponent(jLabel7)))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CmbExtColor, cmbDealer, cmbEngine, cmbIntColor, cmbModel, cmbTrans, cmbVariant});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cmbDealer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbVariant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cmbIntColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(CmbExtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCreate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel7)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initCmb() {
        cmbModel.setModel(new DefaultComboBoxModel<>(new String[]{
            "Ioniq","SantaFe","Creta","Venue"
        }));
        cmbVariant.setModel(new DefaultComboBoxModel<>(new String[]{
            "S","SX","SX(O)","O"
        }));
        cmbIntColor.setModel(new DefaultComboBoxModel<>(new String[]{
            "Black Leather","Cream Leather"
        }));
        CmbExtColor.setModel(new DefaultComboBoxModel<>(new String[]{
            "Red","White","Black"
        }));
        cmbTrans.setModel(new DefaultComboBoxModel<>(new String[]{
            "Automatic","Manual"
        }));
        cmbEngine.setModel(new DefaultComboBoxModel<>(new String[]{
            "Gasoline-Petrol","Gasoline-Diesel","Electric","Hybrid"
        }));
        
        ArrayList<String> names = new ArrayList<String>();
             for(Network network:system.getNetworkList()) {
            for (Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()) {
                System.out.println(enterprise.getName());
                for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
                      for(UserAccount ua: org.getUserAccountDirectory().getUserAccountList()) {
                               System.out.println(ua.getRole().type.toString()+ " : "+ Role.RoleType.Dealer);
                               System.out.println(1213);
                               if(Role.RoleType.Dealer.equals(ua.getRole().type))
                                names.add(ua.getUsername());
                        }
                }
                          
            }
             }
        String[] array = new String[names.size()];
             for(int i = 0; i < array.length; i++) {
               array[i] = names.get(i);
                }
             
        cmbDealer.setModel(new DefaultComboBoxModel<>(array));
    }
    
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        QuoteOrderRequest ior = new QuoteOrderRequest();
        String name = cmbModel.getSelectedItem().toString();
        String variant = cmbVariant.getSelectedItem().toString();
        String intColor = cmbIntColor.getSelectedItem().toString();
        String extColor = CmbExtColor.getSelectedItem().toString();
        String transmission = cmbTrans.getSelectedItem().toString();
        String engine = cmbEngine.getSelectedItem().toString();
        String dealerName = cmbDealer.getSelectedItem().toString();
        int quantity = 1;
        ior.getCar().setModel(name);
        ior.getCar().setVariant(variant);
        ior.getCar().setEngine(engine);
        ior.getCar().setExteriorColor(extColor);
        ior.getCar().setTransmission(transmission);
        ior.getCar().setInteriorColor(intColor);
        ior.getCar().setQuantity(quantity);
        ior.setQuoteOrderId(String.valueOf(random.nextInt(100)));
        ior.setQuantity(quantity);
        ior.setDistributor(account);
        ior.setStatus("Quote Requested");
        ior.setIsOrderCreated(false);
        ior.setIsMarketPrice(false);
        
        //
        //
        UserAccount dealer = null;
        for(Network network:system.getNetworkList()) {
            for (Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()) {
                
                if (enterprise.getEnterpriseType().getValue().equals("Dealer")) {
                    for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if(org.getName().equals("Dealer Organization")){
                            
                           for(UserAccount ua: org.getUserAccountDirectory().getUserAccountList()) {
                                if(ua.getUsername().equals(dealerName)){
                                    dealer = ua;
                                }
                        } 
                            
                        }
                        
                    }
                }
            }
             }
        
        
        //
        //
       
        ior.setDealer(dealer);
        
        System.out.println(dealer.getUsername());
        
        UserAccount distributor=null;
        
        for(Network network:system.getNetworkList()) {
            for (Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()) {
                if (Enterprise.EnterpriseType.Distributor.equals(enterprise.getEnterpriseType())) {
                    for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if(org.getName().equals("Distributor Organization")){
                            
                           for(UserAccount ua: org.getUserAccountDirectory().getUserAccountList()) {
                                if(ua.getUsername().equals(dealer.getDistName())){
                                    distributor = ua;
                                }
                        } 
                            
                        }
                        
                    }
                }
            }
             }
        
        
        ior.setDistributor(distributor);
        ior.setCustomer(account);
        
        ior.setDeliveryDate("Not yet");
        ior.setIsDelivered(false);
        ior.setIsPriceAcceptable(false);
        ior.setIsProcessing(false);
        ior.setIsQuoteReq(true);
        ior.setIsQuoteRes(false);
        ior.setIsReadyToDeliver(false);
        ior.setSales(null);
        ior.setPrice(0);
        
        PricingOrderRequest por = new PricingOrderRequest();
        por.setPricingOrderId(String.valueOf(random.nextInt(100)));
        por.setQuoteOrderId(ior.getQuoteOrderId());
        por.getCar().setModel(name);
        por.getCar().setVariant(variant);
        por.getCar().setEngine(engine);
        por.getCar().setExteriorColor(extColor);
        por.getCar().setTransmission(transmission);
        por.getCar().setInteriorColor(intColor);
        por.getCar().setQuantity(quantity);
        por.setIsPriceGiven(false);

        for(Network network:system.getNetworkList()){
            for(Enterprise ent: network.getEnterpriseDirectory().getEnterpriseList()){
                if (Enterprise.EnterpriseType.Customer.equals(ent.getEnterpriseType())){
                    for(Organization org: ent.getOrganizationDirectory().getOrganizationList()){
                        org.getQuoteOrderQueue().getQuoteOrderRequestList().add(ior);
                        
                    }
                    account.getQuoteOrderQueue().getQuoteOrderRequestList().add(ior);
                }
                if (Enterprise.EnterpriseType.Dealer.equals(ent.getEnterpriseType())){
                    for(Organization org: ent.getOrganizationDirectory().getOrganizationList()){
                        System.out.println(org.getName());
                        org.getQuoteOrderQueue().getQuoteOrderRequestList().add(ior);
                        org.getPriceOrderQueue().getPriceOrderList().add(por);
                    }
                }
                if (Enterprise.EnterpriseType.Distributor.equals(ent.getEnterpriseType())){
                    for(Organization org: ent.getOrganizationDirectory().getOrganizationList()){
                        System.out.println(org.getName());
                        org.getQuoteOrderQueue().getQuoteOrderRequestList().add(ior);
                    }
                }

            }
        }
        

        JOptionPane.showMessageDialog(this, "Quote requested successfully !!", "Information", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbExtColor;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<String> cmbDealer;
    private javax.swing.JComboBox<String> cmbEngine;
    private javax.swing.JComboBox<String> cmbIntColor;
    private javax.swing.JComboBox<String> cmbModel;
    private javax.swing.JComboBox<String> cmbTrans;
    private javax.swing.JComboBox<String> cmbVariant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
