/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Dealer;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.QuoteOrderQueue;
import Business.WorkQueue.QuoteOrderRequest;
import java.awt.CardLayout;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;

/**
 *
 * @author srinivasarithikghantasala
 */
public class DealerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DealerWorkAreaJPanel
     */
    JPanel workArea;
    EcoSystem system;
    UserAccount account;
    public DealerWorkAreaJPanel(JPanel workArea, UserAccount account, EcoSystem system) {
        initComponents();
        this.workArea = workArea;
        this.system = system;
        this.account = account;
        populateAnalytics();
    }
    
    
            private void populateAnalytics(){
                        for(Network network:system.getNetworkList()){
            for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()){
                if (Enterprise.EnterpriseType.Dealer.equals(enterprise.getEnterpriseType())){
                    for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
                        if(org.getName().equals("Dealer Organization")){
                            
                            QuoteOrderQueue queue = org.getQuoteOrderQueue();
                                    Map<String, Long> topSellingModels = queue.getTopSellingCarModels();
int totalRevenue = queue.getTotalRevenueGenerated();
int totalCarsSold = queue.getTotalCarsSold();
List<QuoteOrderRequest> top5Orders = queue.getTop5OrdersByPrice();

// Print results
System.out.println("Top Selling Models: " + topSellingModels);
System.out.println("Total Revenue: $" + totalRevenue);
System.out.println("Total Cars Sold: " + totalCarsSold);
System.out.println("Top 5 Orders by Price: " + top5Orders);

                                   

                                    
                            
                        }
                    }
                    
                }
            }
        }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setText("Manage Orders");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/Admin.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Welcome to Dealer Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(327, 327, 327))))
        );
    }// </editor-fold>//GEN-END:initComponents


    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ManageOrdersJPanel modjp = new ManageOrdersJPanel(workArea,account ,system);
        workArea.add("ManageOrdersJPanel", modjp);
        CardLayout layout = (CardLayout)workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
