/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import ui.Login.LoginCustomerJPanel;
import ui.Login.LoginSystemAdminJPanel;

/**
 *
 * @author srinivasarithikghantasala
 */
public class RolesChooseJPanel extends javax.swing.JPanel {
    
    JPanel WelcomeJPanel;
    JPanel menuJPanel;
    private EcoSystem system;

    /**
     * Creates new form RolesChooseJPanel
     */
    public RolesChooseJPanel(JPanel WelcomeJPanel, JPanel menuJPanel, EcoSystem system) {
        this.WelcomeJPanel = WelcomeJPanel;
        this.system = system;
        this.menuJPanel = menuJPanel;
        initComponents();
        setSize(750, 530);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCustomer = new javax.swing.JButton();
        btnSystemAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btnCustomer.setText("Customer Login");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        btnSystemAdmin.setText("Management Login");
        btnSystemAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSystemAdminActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackgroundImages/main2.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSystemAdmin)
                    .addComponent(btnCustomer))
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCustomer, btnSystemAdmin});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(btnSystemAdmin)
                        .addGap(64, 64, 64)
                        .addComponent(btnCustomer)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        LoginCustomerJPanel lcjp= new LoginCustomerJPanel(WelcomeJPanel, menuJPanel, system);
        WelcomeJPanel.add("LoginSystemAdminJPanel", lcjp);
        CardLayout layout = (CardLayout)WelcomeJPanel.getLayout();
        layout.next(WelcomeJPanel);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnSystemAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemAdminActionPerformed
        // TODO add your handling code here:
        LoginSystemAdminJPanel lsajp = new LoginSystemAdminJPanel(WelcomeJPanel, menuJPanel, system);
        WelcomeJPanel.add("LoginSystemAdminJPanel", lsajp);
        CardLayout layout = (CardLayout)WelcomeJPanel.getLayout();
        layout.next(WelcomeJPanel);
        
    }//GEN-LAST:event_btnSystemAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnSystemAdmin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
